modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "barched"
version = "${version}"
displayName = "Barched"
authors = "zzik2"
description = '''
Bringing Parched, Camel Husk and Spears from 1.21.11 to 1.21.1!
'''
logoFile = "assets/barched/icon.png"

[[dependencies.barched]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.barched]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.barched]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.barched]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "barched.mixins.json"
